/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChangeLg: typeof import('./src/components/ChangeLg.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MenuNav: typeof import('./src/components/MenuNav.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabFour: typeof import('./src/components/TabFour.vue')['default']
    TabOne: typeof import('./src/components/TabOne.vue')['default']
    TabThree: typeof import('./src/components/TabThree.vue')['default']
    TabTwo: typeof import('./src/components/TabTwo.vue')['default']
  }
}
